-- Canonical 35-session catalog mirrored from the native client.
insert into public.sessions
  (id, title, intention, duration_seconds, category_id, pillar, practice_type, audio_path, is_premium, keywords)
values
  ('express_1', '{"fr":"Avant un appel difficile"}', '{"fr":"Un ancrage rapide pour arriver centré et calme à ton prochain appel."}', 60, 'express', 'thoughts', 'anchoring', 'express-avant-un-appel-difficile.mp3', false, array['appel','ancrage','pensées']),
  ('express_2', '{"fr":"Transports bondés"}', '{"fr":"Trouve ton calme intérieur même au milieu de la foule."}', 120, 'express', 'thoughts', 'anchoring', 'express-transports-bondes.mp3', false, array['transport','foule','ancrage']),
  ('express_3', '{"fr":"Petit déjeuner"}', '{"fr":"Une minute de gratitude pour bien commencer ta journée."}', 120, 'express', 'emotions', 'meditation', 'express-petit-dejeuner.mp3', false, array['matin','gratitude','émotions']),
  ('express_4', '{"fr":"Juste avant de dormir"}', '{"fr":"Relâche les tensions de la journée pour mieux t’endormir."}', 180, 'express', 'sleep', 'relaxation', 'express-juste-avant-de-dormir.mp3', false, array['sommeil','soir','relaxation']),
  ('express_5', '{"fr":"Coup de stress au boulot"}', '{"fr":"Quand la pression monte, reprends le contrôle en 90 secondes."}', 120, 'express', 'stress', 'anchoring', 'express-coup-de-stress-au-boulot.mp3', true, array['travail','stress','ancrage']),
  ('express_6', '{"fr":"Après une dispute"}', '{"fr":"Reconnecte-toi à toi-même quand l’émotion a pris le dessus."}', 120, 'express', 'emotions', 'anchoring', 'express-apres-une-dispute.mp3', true, array['dispute','émotions','ancrage']),
  ('express_7', '{"fr":"Réveil en panique"}', '{"fr":"Calme ton cœur quand tu te réveilles avec l’angoisse au ventre."}', 120, 'express', 'stress', 'breathing', 'express-reveil-en-panique.mp3', true, array['réveil','stress','respiration']),
  ('express_8', '{"fr":"Avant une présentation"}', '{"fr":"Calme le trac avant de prendre la parole en public ou en examen."}', 120, 'express', 'stress', 'anchoring', 'express-avant-une-presentation.mp3', true, array['présentation','trac','ancrage']),
  ('decouverte_1', '{"fr":"Ma première méditation"}', '{"fr":"Une introduction douce pour ceux qui n’ont jamais médité."}', 360, 'decouverte', 'thoughts', 'meditation', '01-decouverte-premiere-meditation.mp3', false, array['débutant','découverte','méditation']),
  ('decouverte_2', '{"fr":"Observer sans juger"}', '{"fr":"Apprends à accueillir tes pensées sans t’y attacher."}', 420, 'decouverte', 'thoughts', 'meditation', '02-decouverte-observer-sans-juger.mp3', false, array['observer','pensées','méditation']),
  ('decouverte_3', '{"fr":"Le moment présent"}', '{"fr":"Entraîne-toi à revenir ici et maintenant, encore et encore."}', 360, 'decouverte', 'thoughts', 'anchoring', '03-decouverte-moment-present.mp3', false, array['présent','ancrage','découverte']),
  ('actualite_1', '{"fr":"Quand le monde brûle"}', '{"fr":"Déconnecte ton esprit du bruit informationnel."}', 420, 'actualite', 'thoughts', 'meditation', '23-actualite-quand-le-monde-brule.mp3', false, array['actualité','surcharge','méditation']),
  ('actualite_2', '{"fr":"La guerre en bruit de fond"}', '{"fr":"Trouve la sérénité malgré un monde en constante évolution."}', 480, 'actualite', 'thoughts', 'meditation', '24-actualite-la-guerre-en-bruit-de-fond.mp3', true, array['actualité','guerre','méditation']),
  ('actualite_3', '{"fr":"Débrancher quand tout crie"}', '{"fr":"Une pause consciente loin des écrans et des titres."}', 480, 'actualite', 'thoughts', 'anchoring', '25-actualite-debrancher-quand-tout-crie.mp3', false, array['écrans','actualité','ancrage']),
  ('actualite_4', '{"fr":"Recul sur l’actualité"}', '{"fr":"Apprends à poser ton téléphone avec légèreté."}', 780, 'actualite', 'thoughts', 'meditation', '26-actualite-recul-sur-lactualite.mp3', true, array['actualité','téléphone','méditation']),
  ('actualite_5', '{"fr":"Pause info"}', '{"fr":"Prends de la hauteur sur les événements du monde."}', 420, 'actualite', 'thoughts', 'meditation', '27-actualite-pause-info.mp3', true, array['actualité','information','méditation']),
  ('stress_1', '{"fr":"Quand le stress prend le dessus"}', '{"fr":"Une séance pour revenir à toi quand la pression monte."}', 420, 'stress', 'stress', 'breathing', '08-stress-quand-le-stress-prend-le-dessus.mp3', false, array['stress','pression','respiration']),
  ('stress_2', '{"fr":"Respiration 4-7-8"}', '{"fr":"Parcours ton corps pour relâcher les tensions."}', 300, 'stress', 'stress', 'breathing', '09-stress-respiration-4-7-8.mp3', true, array['stress','4-7-8','respiration']),
  ('stress_3', '{"fr":"Relâche"}', '{"fr":"Contracte et relâche chaque groupe musculaire."}', 540, 'stress', 'stress', 'relaxation', '10-stress-relache.mp3', false, array['stress','muscles','relaxation']),
  ('stress_4', '{"fr":"Ancrage"}', '{"fr":"Reviens à toi grâce à une technique d’ancrage simple."}', 360, 'stress', 'stress', 'anchoring', '11-stress-ancrage.mp3', false, array['stress','ancrage']),
  ('stress_5', '{"fr":"Le voyageur qui s’arrête"}', '{"fr":"Dissous les tensions mentales et retrouve un état de calme."}', 720, 'stress', 'stress', 'relaxation', '12-stress-le-voyageur-qui-sarrete.mp3', true, array['stress','calme','relaxation']),
  ('sleep_1', '{"fr":"Détente du soir"}', '{"fr":"Prépare ton corps et ton esprit au repos."}', 780, 'sleep', 'sleep', 'relaxation', '13-sommeil-detente-du-soir.mp3', false, array['sommeil','soir','relaxation']),
  ('sleep_2', '{"fr":"Visualisation apaisante"}', '{"fr":"Voyage mental dans un lieu calme et sécurisant."}', 420, 'sleep', 'sleep', 'visualization', '14-sommeil-visualisation-apaisante.mp3', false, array['sommeil','visualisation']),
  ('sleep_3', '{"fr":"Rituel pré-sommeil"}', '{"fr":"Un rituel simple pour quitter doucement la journée."}', 420, 'sleep', 'sleep', 'relaxation', '15-sommeil-rituel-pre-sommeil.mp3', false, array['sommeil','rituel','relaxation']),
  ('sleep_4', '{"fr":"Entre deux mondes"}', '{"fr":"Laisse les pensées ralentir avant la nuit."}', 420, 'sleep', 'sleep', 'visualization', '16-sommeil-entre-deux-mondes.mp3', false, array['sommeil','pensées','visualisation']),
  ('sleep_5', '{"fr":"Plongée dans le silence"}', '{"fr":"Une pause silencieuse pour accompagner le coucher."}', 360, 'sleep', 'sleep', 'meditation', '17-sommeil-plongee-dans-le-silence.mp3', true, array['sommeil','silence','méditation']),
  ('breathing_1', '{"fr":"Cohérence cardiaque"}', '{"fr":"Une respiration guidée pour retrouver un rythme régulier."}', 240, 'breathing', 'stress', 'breathing', '04-respiration-coherence-cardiaque.mp3', false, array['cohérence','respiration','stress']),
  ('breathing_2', '{"fr":"Respiration alternée"}', '{"fr":"Explore une respiration lente et attentive."}', 300, 'breathing', 'stress', 'breathing', '05-respiration-respiration-alternee.mp3', false, array['alternée','respiration']),
  ('breathing_3', '{"fr":"Souffle apaisant"}', '{"fr":"Un temps pour ralentir et écouter ton souffle."}', 480, 'breathing', 'stress', 'breathing', '06-respiration-souffle-apaisant.mp3', false, array['souffle','respiration','apaisement']),
  ('breathing_4', '{"fr":"Expansion thoracique"}', '{"fr":"Redonne de l’espace à ta respiration."}', 540, 'breathing', 'stress', 'breathing', '07-respiration-expansion-thoracique.mp3', false, array['thorax','respiration']),
  ('emotion_1', '{"fr":"Apprendre à s’aimer"}', '{"fr":"Accueille-toi avec davantage de douceur."}', 480, 'emotion', 'emotions', 'self_compassion', '18-emotion-apprendre-a-saimer.mp3', false, array['émotions','bienveillance']),
  ('emotion_2', '{"fr":"Joie et énergie"}', '{"fr":"Reconnecte-toi à ce qui te fait du bien."}', 540, 'emotion', 'emotions', 'meditation', '19-emotion-joie-et-energie.mp3', false, array['joie','énergie','émotions']),
  ('emotion_3', '{"fr":"De l’anxiété au sourire"}', '{"fr":"Observe ton ressenti avec douceur et curiosité."}', 840, 'emotion', 'emotions', 'meditation', '20-emotion-de-lanxiete-au-sourire.mp3', false, array['anxiété','émotions','méditation']),
  ('emotion_4', '{"fr":"Peur et courage"}', '{"fr":"Fais une place à ce qui est là, sans te brusquer."}', 420, 'emotion', 'emotions', 'self_compassion', '21-emotion-peur-et-courage.mp3', false, array['peur','courage','bienveillance']),
  ('emotion_5', '{"fr":"L’amour"}', '{"fr":"Un moment de bienveillance envers toi et les autres."}', 480, 'emotion', 'emotions', 'self_compassion', '22-emotion-lamour.mp3', false, array['amour','bienveillance','émotions'])
on conflict (id) do update set
  title = excluded.title,
  intention = excluded.intention,
  duration_seconds = excluded.duration_seconds,
  category_id = excluded.category_id,
  pillar = excluded.pillar,
  practice_type = excluded.practice_type,
  audio_path = excluded.audio_path,
  is_premium = excluded.is_premium,
  keywords = excluded.keywords,
  catalog_version = public.sessions.catalog_version + 1,
  updated_at = now();
